# Generated by Django 3.0 on 2019-12-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, verbose_name='user_id')),
                ('other_id', models.CharField(max_length=50, verbose_name='other_id')),
                ('msg', models.CharField(max_length=250, verbose_name='msg')),
                ('ts', models.CharField(max_length=100, verbose_name='ts')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('info', models.TextField(blank=True)),
            ],
        ),
    ]
